//
//  AboutViewController.swift
//  VIP Project
//
//  Created by Victor on 22/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutViewControllerProtocol: UIViewControllerRouting {
    func setupDI(
        interactor: AboutInteractorProtocol,
        router: AboutRouterProtocol
    )
    
    func displayAboutData(viewModel: About.AboutData.ViewModel)
    func goToLink(viewModel: About.Navigate.ViewModel)
}

class AboutViewController: UIViewController, AboutViewControllerProtocol {
   
    // MARK: - DI
    
    var interactor: AboutInteractorProtocol?
    var router: AboutRouterProtocol?
    
    func setupDI(
        interactor: AboutInteractorProtocol,
        router: AboutRouterProtocol
    ) {
        self.interactor = interactor
        self.router = router
    }
    
    // MARK: - Properties
    
    @IBOutlet weak var aboutLabel: UILabel!
    @IBOutlet weak var myImageView: UIImageView!
    
    //MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        getAboutData()
    }
    
    //MARK: - Requests
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func getAboutData() {
        interactor?.getAboutData()
    }
    
    @IBAction func didTouchLink(_ sender: Any) {
        interactor?.goToLink()
    }
    
    func goToLink(viewModel: About.Navigate.ViewModel) {
        let url = viewModel.url
        UIApplication.shared.open(url)
    }

    //MARK: - Displays
    
    func displayAboutData(viewModel: About.AboutData.ViewModel) {
        aboutLabel.text = viewModel.aboutText
        myImageView.image = viewModel.myImage
    }
}
