//
//  AboutRouter.swift
//  VIP Project
//
//  Created by Victor on 22/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AboutRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AboutDataPassing {
    var dataStore: AboutDataStore? { get }
}

class AboutRouter: NSObject, AboutRoutingLogic, AboutDataPassing {
    weak var viewController: AboutViewController?
    var dataStore: AboutDataStore?
}
