//
//  AboutViewController.swift
//  VIP Project
//
//  Created by Victor on 22/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutDisplayLogic: class {
    func displayAboutData(viewModel: About.AboutData.ViewModel)
    func goToLink(viewModel: About.Navigate.ViewModel)
}

class AboutViewController: UIViewController, AboutDisplayLogic {
   
    @IBOutlet weak var aboutLabel: UILabel!
    @IBOutlet weak var myImageView: UIImageView!
    
    var interactor: AboutBusinessLogic?
    var router: (NSObjectProtocol & AboutRoutingLogic & AboutDataPassing)?
    
    //MARK: - Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    //MARK: - Setup
    
    private func setup() {
        let viewController = self
        let interactor = AboutInteractor()
        let presenter = AboutPresenter()
        let router = AboutRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    //MARK: - Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    //MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        getAboutData()
    }
    
    //MARK: - Requests
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func getAboutData() {
        interactor?.getAboutData()
    }
    
    @IBAction func didTouchLink(_ sender: Any) {
        interactor?.goToLink()
    }
    
    func goToLink(viewModel: About.Navigate.ViewModel) {
        let url = viewModel.url
        UIApplication.shared.open(url)
    }

    //MARK: - Displays
    
    func displayAboutData(viewModel: About.AboutData.ViewModel) {
        aboutLabel.text = viewModel.aboutText
        myImageView.image = viewModel.myImage
    }
}
