//
//  AboutViewController.swift
//  VIP Project
//
//  Created by Victor on 22/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutViewControllerProtocol: UIViewControllerRouting {
    func setupDI(
        interactor: AboutInteractorProtocol,
        router: AboutRouterProtocol
    )
}

class AboutViewController: UIViewController, AboutViewControllerProtocol {
   
    // MARK: - DI
    
    private var interactor: AboutInteractorProtocol?
    private var router: AboutRouterProtocol?
    
    func setupDI(
        interactor: AboutInteractorProtocol,
        router: AboutRouterProtocol
    ) {
        self.interactor = interactor
        self.router = router
    }
    
    //MARK: - View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    //MARK: - Actions
    
    @IBAction func didTouchLink(_ sender: Any) {
        guard let url = URL(string: StringConstants.gitHub.rawValue) else { return }
        
        router?.route(to: .link(url))
    }
}
