//
//  ArticlesRouter.swift
//  VIP Project
//
//  Created by Victor on 21/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ArticlesRoutingLogic {
    func routeToArticleDetails()
}

protocol ArticlesDataPassing {
    var dataStore: ArticlesDataStore? { get }
}

class ArticlesRouter: NSObject, ArticlesRoutingLogic, ArticlesDataPassing {
    weak var viewController: ArticlesViewController?
    var dataStore: ArticlesDataStore?
    
    //MARK: - Routing
    
    func routeToArticleDetails() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        if let destinationVC = storyboard.instantiateViewController(identifier: "articleDetailsVC") as? ArticleDetailsViewController, var destinationDataStore = destinationVC.router?.dataStore, let sourceDataStore = dataStore {
            passDataToArticleDetails(source: sourceDataStore, destination: &destinationDataStore)
            viewController?.navigationController?.pushViewController(destinationVC, animated: true)
        }
    }
    
    //MARK: - Passing data
    
    func passDataToArticleDetails(source: ArticlesDataStore, destination: inout ArticleDetailsDataStore) {
        destination.article = source.selectedArticle
    }
}
