//
//  ArticlesRouter.swift
//  VIP Project
//
//  Created by Victor on 21/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticlesRouterProtocol {
    func set(viewController: ArticlesViewControllerProtocol)
    
    func route(to scene: ArticlesRouter.Scene)
}

class ArticlesRouter: NSObject, ArticlesRouterProtocol {
    
    //MARK: - DI
    
    weak var viewController: ArticlesViewControllerProtocol?
    private let articleDetailsStoryboard: Storyboard
    
    func set(viewController: ArticlesViewControllerProtocol) {
        self.viewController = viewController
    }
    
    init(
        articleDetailsStoryboard: Storyboard
    ) {
        self.articleDetailsStoryboard = articleDetailsStoryboard
    }
}

//MARK: - Routing

extension ArticlesRouter {
    
    enum Scene {
        case details(Article)
    }
    
    func route(to scene: ArticlesRouter.Scene) {
        switch scene {
            case .details(let article):
                guard let vc = articleDetailsStoryboard.viewController(identifier: "ArticleDetailsViewController" as! StoryboardId) as? ArticleDetailsViewController else { return }
                
                vc.article = article
                viewController?.show(vc, sender: nil)
        }
    }
}
