//
//  ArticlesModels.swift
//  VIP Project
//
//  Created by Victor on 21/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Articles {
    enum List {
        struct Response {
            var articles: [Article]?
            var error: Error?
        }
        
        struct ViewModel {
            var articles: [Article]?
        }
    }
    
    enum Search {
        struct Request {
            var text: String?
        }
        
        struct Response {
            var articles: [Article]?
        }
        
        struct ViewModel {
            var articles: [Article]?
        }
    }
    
    enum SelectedArticle {
        struct Request {
            var index: Int
        }
    }
}
