//
//  ArticlesPresenter.swift
//  VIP Project
//
//  Created by Victor on 21/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticlesPresentationLogic {
    func presentArticles(response: Articles.List.Response)
    func presentFilteredArticles(response: Articles.Search.Response)
    func presentSelectedArticle()
}

class ArticlesPresenter: ArticlesPresentationLogic {
    weak var viewController: ArticlesDisplayLogic?
    
    //MARK: - Presenters
    
    func presentArticles(response: Articles.List.Response) {
        var viewModel = Articles.List.ViewModel()
        viewModel.articles = response.articles
        viewController?.displayArticles(viewModel: viewModel)
    }
    
    func presentFilteredArticles(response: Articles.Search.Response) {
        guard let articles = response.articles else {
            return
        }
        
        var viewModel = Articles.Search.ViewModel()
        viewModel.articles = articles
        viewController?.displayArticles(viewModel: viewModel)
    }
    
    func presentSelectedArticle() {
        viewController?.displaySelectedArticle()
    }
}
