//
//  ArticleDetailsPresenter.swift
//  VIP Project
//
//  Created by Victor on 22/08/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ArticleDetailsPresentationLogic {
    func presentArticle(response: ArticleDetails.DisplayArticle.Response)
}

class ArticleDetailsPresenter: ArticleDetailsPresentationLogic {
    weak var viewController: ArticleDetailsDisplayLogic?
    
    //MARK: - Presenters
    
    func presentArticle(response: ArticleDetails.DisplayArticle.Response) {
        let viewModel = ArticleDetails.DisplayArticle.ViewModel(article: response.article)
        viewController?.displayArticle(viewModel: viewModel)
    }
}
